name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build and run tests
        run: mvn clean verify --batch-mode

      - name: Package fat JAR
        run: mvn package --batch-mode

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: leave-tracker-jar
          path: target/leave-tracker.jar